# OpenRAGLecture/.air.toml

# Working directory
root = "."
tmp_dir = "tmp"

[build]
# Command to build the Go binary
cmd = "go build -o ./tmp/main ./cmd/api"
# The binary to run
bin = "tmp/main"
# Files to watch for changes
include_ext = ["go", "tpl", "tmpl", "html"]
# Directories to exclude from watching
exclude_dir = ["tmp", "vendor", "uploads"]
# Delay between file change detection and rebuild
delay = 1000 # ms

[log]
# Log colors
time = true

[misc]
# Delete tmp directory on exit
clean_on_exit = true