# configs\config.debug.yaml

server:
  port: "8180"
  mode: "debug"

database:
  mysql:
    host: "db"
    port: "3306"

vector_db:
  qdrant:
    host: "qdrant"
    port: 6333
    grpc_port: 6334
    collection_name: "lecture_chunks_dev"

cache:
  redis:
    host: "redis"
    port: 6379

auth:
  jwt:
    secret_key: "a-very-secret-key-for-dev"
    access_token_expiry_hours: 24
    refresh_token_expiry_days: 7

storage:
  type: "local"
  local:
    path: "/app/uploads"

google:
  api_key: "" # Should be overridden by .env file
  project_id: "" # ★★★ 追加: .envファイルで上書きされるべき ★★★
  location: "us-central1" # ★★★ 追加 ★★★
  embedding_model: "text-embedding-005" # ★★★ 修正 ★★★
  llm_model: "gemini-1.5-flash"

logging:
  level: "debug"
  encoding: "console"

telemetry:
  enabled: false